In [1]:
import os
os.chdir('/home/evgenii/ITMO')

import numpy as np
from drone_rescue_ai.environment.environment import Environment
from drone_rescue_ai.environment.environment_map import OBSTACLE_MAP, OBJECT_MAP, COLOR_MAP
from drone_rescue_ai.agent.agent import Agent

In [2]:
AREA_SIZE = (100, 100)
NUM_TARGETS = 3
NUM_OBSTACLES = 50
OBSERVATION_AREA = (9,9)

import os
api_key = os.getenv("OPENAI_API_KEY")
print(api_key)
agent = Agent(area_size=AREA_SIZE, object_map=OBJECT_MAP, observation_area=OBSERVATION_AREA, api_key=api_key, chat_gpt_model="gpt-4o-2024-08-06")

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


In [3]:
env = Environment(obstacles_map=OBSTACLE_MAP,
                color_map=COLOR_MAP,
                object_map=OBJECT_MAP,
                area_size=AREA_SIZE,
                num_targets=NUM_TARGETS,
                num_obstacles=NUM_OBSTACLES
                )

In [4]:
# env.render_env('./rendered_env.jpg')

In [5]:
# new_pos, done, observation, bin_observation, metadata = env.step(1, (0,0), (9,9))

In [6]:
# observation[metadata["agent_position_in_local_observation"]] = 4 
# env.render_observation(observation, './observation_with_agent.jpg')

In [7]:
# # cur_position = (0,0)
# for _ in range(10):
#     action = 1
#     new_pos, done, observation, bin_observation, metadata = env.step(action, cur_position, (9,9))
#     cur_position = new_pos
#     agent.update_visited_map(observation, bin_observation)

# visited_map = agent.get_visited_map()
# visited_map[cur_position] = 4 
# env.render_visited_map(visited_map, './visited_map_with_agent_position.jpg')

# observation[metadata["agent_position_in_local_observation"]] = 4 
# env.render_observation(observation, './observation_with_agent.jpg')

In [8]:
# agent_position = (0,0)
# for _ in range(150):
#     action = agent.generate_action()
#     print('Action: ', action)
#     observation_area_of_agent = agent.get_observation_area()
#     print('Agent observation area ', observation_area_of_agent)
#     new_position, done, observation, obs_binary_mask = env.step(action, agent_position, observation_area_of_agent)

#     agent_position = new_position

#     print(f"New position : {new_position}, Done: {done}\n")
#     # print(observation, '\n')
#     agent.update_visited_map(observation, obs_binary_mask)
#     print(agent.visited_map)

# env.render_visited_map(agent.get_visited_map(), './visited_map.jpg')
# env.render_observation(observation, './observation_exp1.jpg')

In [9]:
# agent_position = (0,0)
# for _ in range(150):
#     action = agent.generate_action()
#     print('Action: ', action)
#     observation_area_of_agent = agent.get_observation_area()
#     print('Agent observation area ', observation_area_of_agent)
#     new_position, done, observation, obs_binary_mask = env.step(action, agent_position, observation_area_of_agent)

#     agent_position = new_position

#     print(f"New position : {new_position}, Done: {done}\n")
#     # print(observation, '\n')
#     agent.update_visited_map(observation, obs_binary_mask)
#     print(agent.visited_map)

# env.render_visited_map(agent.get_visited_map(), './visited_map.jpg')
# env.render_observation(observation, './observation_exp1.jpg')

In [10]:
# from langchain_core.prompts import ChatPromptTemplate
# system_template = "Translate the following from English into {language}"

# prompt_template = ChatPromptTemplate.from_messages(
#     [("system", system_template), ("user", "{text}")]
# )

In [11]:
# import os
# api_key = os.getenv("OPENAI_API_KEY")
# api_key

In [12]:
# import os
# from langchain_openai import ChatOpenAI

# api_key = os.getenv("OPENAI_API_KEY")
# model = ChatOpenAI(model="gpt-3.5-turbo", api_key=api_key)

In [13]:
# from langchain_core.messages import HumanMessage, SystemMessage

# messages = [
#     SystemMessage(content="Translate the following from English into Italian"),
#     HumanMessage(content="hi!"),
# ]

# output_message = model.invoke(messages)

In [14]:
# output_message.response_metadata.get("token_usage").get("total_tokens")

In [15]:
# # cost = 3.000
# amount = 1e6
# print(f"{cost/amount * 447:.10f}")

In [16]:
agent_position = (0,0)
env = Environment(obstacles_map=OBSTACLE_MAP,
                color_map=COLOR_MAP,
                object_map=OBJECT_MAP,
                area_size=AREA_SIZE,
                num_targets=NUM_TARGETS,
                num_obstacles=NUM_OBSTACLES
                )
observation_area_of_agent = agent.get_observation_area()
new_position, done, observation, obs_binary_mask, metadata = env.step(4, agent_position, observation_area_of_agent)
agent_position = new_position
env.render_env('./exp_1/environment.jpg')

# Update visited map
agent.update_visited_map(observation, obs_binary_mask)

# Add current agent position to the visited map
visited_map = agent.get_visited_map()
visited_map[agent_position] = 4 

# Add current agent position to the local observation
observation[metadata["agent_position_in_local_observation"]] = 4 


for step in range(200):
    print(visited_map)
    response = agent.generate_action_by_model(visited_map, observation)
    action = response["action"]
    explaination = response["explaination"]
    print(f"Step {step} - {action}. Explainataion: {explaination}")

    new_position, done, observation, obs_binary_mask, metadata = env.step(action, agent_position, observation_area_of_agent)
    agent_position = new_position

    # Update visited map
    agent.update_visited_map(observation, obs_binary_mask)

    # Add current agent position to the visited map
    visited_map_wiht_cut_agent_position = agent.get_visited_map()
    visited_map_wiht_cut_agent_position[agent_position] = 4 

    # Add current agent position to the local observation
    observation_with_cur_agent_position = observation.copy()
    observation_with_cur_agent_position[metadata["agent_position_in_local_observation"]] = 4 

    env.render_visited_map(visited_map_wiht_cut_agent_position, f'./exp_1/visited_map_{step}.jpg')
    env.render_observation(observation_with_cur_agent_position, f'./exp_1/observation_{step}.jpg')

[[4 0 0 ... 3 3 3]
 [0 0 0 ... 3 3 3]
 [0 0 0 ... 3 3 3]
 ...
 [3 3 3 ... 3 3 3]
 [3 3 3 ... 3 3 3]
 [3 3 3 ... 3 3 3]]
Step 0 - 1. Explainataion: The current observation shows that the drone is surrounded by all 0s (BACKGROUND) with no obstacles or target points in the immediate vicinity. Moving downwards (action 1) will help in exploring more unvisited areas in the grid.
[[4 0 0 ... 3 3 3]
 [4 0 0 ... 3 3 3]
 [0 0 0 ... 3 3 3]
 ...
 [3 3 3 ... 3 3 3]
 [3 3 3 ... 3 3 3]
 [3 3 3 ... 3 3 3]]
Step 1 - 3. Explainataion: The drone is currently surrounded by visited areas, and there are no obstacles or target points in the immediate observation. Therefore, the drone should move to explore new areas. Moving right seems to be a viable option as it will allow the drone to explore unvisited areas without hitting obstacles.
[[4 0 0 ... 3 3 3]
 [0 4 0 ... 3 3 3]
 [0 0 0 ... 3 3 3]
 ...
 [3 3 3 ... 3 3 3]
 [3 3 3 ... 3 3 3]
 [3 3 3 ... 3 3 3]]
Step 2 - 3. Explainataion: The drone should move right

In [19]:
response["explanaition"]

'The current observation shows that the entire top half of the observation area contains obstacles (1s). The bottom half of the observation area is clear (0s), indicating a possible path. Moving down will allow the drone to explore this unvisited area.'

In [ ]:
"""'The current observation shows that the entire
 top half of the observation area 
 contains obstacles (1s). The bottom
   half of the observation area is 
   clear (0s), indicating a possible 
   path. Moving down will allow the drone to
     explore this unvisited area.'
     """

SyntaxError: incomplete input (3866867020.py, line 1)